#! /bin/bash
gcloud compute firewall-rules create allow-jenkins-ui-public \
  --direction=INGRESS \
  --priority=1000 \
  --network=default \
  --action=ALLOW \
  --rules=tcp:8080 \
  --source-ranges=0.0.0.0/0\
  --target-tags=jenkins-server
