#! /bin/bash
gcloud compute firewall-rules create allow-nexus-ui-jenkins \
  --direction=INGRESS \
  --priority=1000 \
  --network=default \
  --action=ALLOW \
  --rules=tcp:8081 \
  --source-tags=jenkins-server\
  --target-tags=nexus-server
