#! bin/bash
gcloud compute instances create sonarqube-server \
  --zone=us-central1-a \
  --machine-type=e2-standard-4 \
  --image-family=debian-12 \
  --image-project=debian-cloud \
  --boot-disk-size=30GB \
  --tags=sonarqube-server,ssh \
  --metadata-from-file=startup-script=../startup-scripts/sonar.sh
