#! /bin/bash
gcloud compute firewall-rules create allow-http-jenkins \
  --direction=INGRESS \
  --priority=1000 \
  --network=default \
  --action=ALLOW \
  --rules=tcp:80 \
  --source-tags=jenkins-server\
  --target-tags=sonarsube-server
