#! /bin/bash
gcloud compute firewall-rules create  allow-ssh-myip \
  --direction=INGRESS \
  --priority=1000 \
  --network=default \
  --action=ALLOW \
  --rules=tcp:22 \
  --source-ranges=156.206.243.48/32\
  --target-tags=ssh
